apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: brewz
  namespace: loyal-elk
spec:
  project: default
  source:
    path: manifests/brewz
    repoURL: https://github.com/fbchan/techxchange-gitops-lab.git
    targetRevision: HEAD
  destination:
    namespace: loyal-elk
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
